### ISSUE TITLE
Question - Example use-case

### ISSUE THREAD

**Issue by thim81** [samitpal/influxdb-router#23]
Dear Samit,

I have looked at your router and I'm trying to figure out if this would allow us to use it for a specific use-case.

We collect stats for a whole range of customers centrally influx but have the option give customers access to their own data using grafana. We want to segregate data to give customers access to their own data AND still have access to all data from an admin view-point.

I'm correct that your influxdb-router, would allow the option define as a "in-between" gateway/proxy that acts as a "filter" while inserting and/or fetching influx data?

Example: 
- "Customer X" has access to influxdata with tags "customer x"?
- "Customer Y" has access to influxdata with tags "customer x" & "customer y"
- "Admin" has access to all influxdata

**Comment by samitpal** [comment]
Yes, influxDB-router is just a proxy between the clients and influxDB. You can easily segregate data either by just the database (per customer db) or even by influxDB machine and database.  If it is a shared grafana system you can just create multiple organizations one each for your customer.  Within and org you create data sources with the corresponding customer db. Then you create users in the appropriate orgs. Let me know if this makes sense.

**Comment by samitpal** [comment]
Resolving it.
